using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(BoundsCheck))]
public class ProjectileHero : MonoBehaviour
{
    private BoundsCheck bndCheck;
    private Renderer rend;
    public bool isPhaser = false;
    public float phaserFrequency = 8f;
    public float phaserMagnitude = .5f;
    private float birthTime;
    private float birthStartY;


    [Header("Dynamic")]
    public Rigidbody rigid;
    [SerializeField]                                                         // a
    private eWeaponType _type;                                               // b

    // This public property masks the private field _type
    public eWeaponType type
    {                                                // c
        get { return (_type); }
        set { SetType(value); }
    }

    void Awake()
    {
        bndCheck = GetComponent<BoundsCheck>();
        rend = GetComponent<Renderer>();                                     // d
        rigid = GetComponent<Rigidbody>();
    }

    // I'm adding this to track when the projectile was created. For phasers.
    void Start()
    {
        birthTime = Time.time;
        birthStartY = transform.position.y;
    }


    void Update()
    {
        // Phaser movement
        if (isPhaser)
        {
            Vector3 pos = transform.position;
            pos += rigid.velocity * Time.deltaTime;
            float distance = pos.y - birthStartY;
            float sin = Mathf.Sin(distance * phaserFrequency);
            pos.x += sin * phaserMagnitude;
            transform.position = pos;
        }

        if (bndCheck.LocIs(BoundsCheck.eScreenLocs.offUp))
        {
            Destroy(gameObject);
        }
    }


    /// <summary>
    /// Sets the _type private field and colors this projectile to match the 
    ///   WeaponDefinition.
    /// </summary>
    /// <param name="eType">The eWeaponType to use.</param>
    public void SetType(eWeaponType eType)
    {                                 // e
        //Debug.Log("Projectile rend: " + rend);
        //Debug.Log("Renderer on projectile prefab: " + GetComponent<Renderer>());
        _type = eType;
        WeaponDefinition def = Main.GET_WEAPON_DEFINITION(_type);
        rend.material.color = def.projectileColor;
    }

    /// <summary>
    /// Allows Weapon to easily set the velocity of this ProjectileHero
    /// </summary>
    public Vector3 vel
    {
        get { return rigid.velocity; }
        set { rigid.velocity = value; }
    }
}
